### ISSUE TITLE
비교 기능 옵션 우선순위

### ISSUE THREAD

**Issue by WMPeople** [WMPeople/Assignment#5]
ABCDEFG 와 abcdefg는 대소문자를 구분하지 않으면 같은 문자열입니다.
여기에 공백 및 개행을 무시하는 옵션을 추가하여 다음과 같은 상황에서 비교를 하면,
A  BCDE  FG 와 abcdefg의 결과
![image](https://user-images.githubusercontent.com/37654100/38967876-085ac036-43c4-11e8-91d7-9c59a4c28660.png)

위와 같이 A 만 같고 나머지는 같지 않다고 나옵니다.

이는 알고리즘 수행 순서와 연관되어 있습니다.

원래 텍스트 -> 정규식 옵션에 의한 치환 -> DIFF 비교 알고리즘 수행 -> 공백 및 개행 무시 옵션 적용 -> 정규식 치환한것을 복구 -> 최종적 비교 결과.

* 위의 방식에서 다음 방식으로 전환할 계획입니다.

원래 텍스트 -> **공백 및 개행 옵션에 의한 치환** -> 정규식 옵션에 의한 치환 -> DIFF 비교 알고리즘 수행 -> 정규식 치환한것을 복구 -> **공백 및 개행 옵션에 의한 복구** -> 최종적 비교 결과.

**Comment by WMPeople** [comment]
공백 및 개행 옵션에 의한 복구에 대한 고찰

비교 상태가 "동일, 삽입, 삭제" 에서 "동일, 삽입, 삭제, **삽입동일, 삭제동일**" 변경되었으므로
이를 고민하여야 합니다.

삽입, 삭제 동일(변경동일) 이란 변경되었으나 같다고 표기해야 하는 예외경우를 말합니다.
변경동일 인 경우에도 공백 및 개행 옵션에 의해 치환된 것은 복구 되어야 합니다.
복구 시에도 변경동일 상태로 추가를 하여야 합니다.

이를 수행하려면 리펙토링이 동반되어야 할것 같습니다.

**Comment by KimHongHun** [comment]
1차 리펙토링 및 변경 동일 추가 완료 되었으나,
동일 경우에 복원을 어떻게 해야 하는지 새로운 로직이 필요할 합니다.
이전에는 동일 경우에는 왼쪽, 오른쪽 변경사항이 무조껀 있었으나, 이제는 그렇지 않는 경우가 있습니다.

예전 ex ) "<br>" "</br>" 은 -> "\0" "\0"으로 대체 되기 때문에 둘다 변경해야 하나,
지금 ex) "ABC  DEF" "ABCDEF" 은 왼쪽만 변경을 해야 하는 경우가 발생합니다.

이처럼 복구의 순서가 지켜져야 합니다. 
이는 먼저 복구 되어야 하는 것임을 계산할 필요성이 있다는 것입니다.
ex) "A  BCD  EF" , "ABC   DEF"
-> "A", D" ", "BC", I"  ", "D", D" ", "EF"     ( "" 공통, D " ", 삭제, I " " 삽입)
block.index와 leftCurLength, rightCurLength를 매개변수로하여 어느쪽이 먼저인지를 판단이 가능하여야 합니다.
블럭에서 왼쪽 변경 지점,  블럭에서 오른쪽 변경 지점
return leftCurLength - leftBlock.index < rightCurLength - rightBlock.index;
환원을 1개씩 진행해야 합니다.(2개씩 할 수 없음)

**Comment by KimHongHun** [comment]
위와 같은 알고리즘을 통하여 공백 무시 기능을 구현하였으나,
다음과 같이 공백과 변경이 겹치는 경우 정상적으로 표시되지 않는 버그가 있습니다.

![image](https://user-images.githubusercontent.com/37653952/38985525-9b77e6e2-4404-11e8-8441-f3bfa8f31aeb.png)

이는 환원하는 과정에서 변경된 것으로 처리하여 추가 되었기 때문입니다.
이를 개선하기 위해서는 변경되었으나 변경으로 표시하지 않는 -2, 2를 활용하는 방안을 고찰하여야 할것으로 생각됩니다.
